### ISSUE TITLE
Feature Request: Set Wekan ROOT_URL to FQDN on Univention. Not internal IP address.

### ISSUE THREAD

**Issue by xet7** [wekan/univention#1]
I got email, it seems that Wekan ROOT_URL is set to server internal IP address.
Wekan ROOT_URL examples are at:
https://github.com/wekan/wekan/wiki/Settings
so it needs to be set to your https://FQDN, like https://example.com, so that all Wekan URLs work correctly.

**Comment by xet7** [comment]
I found that ROOT_URL setting is at Univention VM at this path:
```
/var/lib/univention-appcenter/apps/wekan/wekan/compose-docker-compose.yml
```
At wekan-app container environment part, there is this line:
```
- ROOT_URL=https://ucs-......
```
But using this did not stop and start Wekan:
```
cd /var/lib/univention-appcenter/apps/wekan/wekan
docker-compose stop
docker-compose start
```
So maybe it's managed somewhere else. Anyway, I'll try to figure it out.

There is also `.run` and `.template` file in same directory, and it looks like setup of Wekan would also make FQDN settings. At least on my UCS intranet URL it's under https.

I would think that in next version of Wekan for UCS I could add some web UI configuration option for this.

**Comment by xet7** [comment]
Original problem at email I got was:

> The problem is whenever you click on a Wekan CheckList from a board, it spawns the internal ip address of the server and does not use the FQDN the first page does and then breaks the SSL by changing the domain name. This makes it unusable.

**Comment by 1kidvidiot** [comment]
Hello all - I sent in the original email for this issue - so the FQDN shows great from the first couple screens, but when you have added Check Lists and click on them, it launches under the internal domain (no more SSL) and does not use the FQDN - thanks for looking at it, I think it will make a great Monday substitute if I can get it all secure behind SSL.

It also seems to log the person out at this stage, as it must see it as a different domain...I am logged in in first screen (admin), but it no longer recognizes the credentials after clicking on the Check List. if I change the board to private, it disappears completely (Board Not Found...)


![Wekan 1](https://user-images.githubusercontent.com/18040392/62231847-b1fbe180-b379-11e9-890f-9930e5907869.JPG)

![Wekan 2](https://user-images.githubusercontent.com/18040392/62231862-b627ff00-b379-11e9-8a9f-da0caec3336d.JPG)

**Comment by xet7** [comment]
I would think that because card does open OK, using FQDN is OK, it's just that I need up update Univention Wekan version to newest Wekan version. I presume this is just some old bug that is already fixed in newest Wekan.

**Comment by 1kidvidiot** [comment]
Awesome! Well appreciate it, seems like a nice bit of software for us - should I keep an eye out for an update in the UCS dashboard?

**Comment by xet7** [comment]
At UCS dashboard where is all updates, there will be Wekan update. It will take some days for me to make update and test it, before it comes available.

**Comment by 1kidvidiot** [comment]
Awesome thanks so much! Will do

**Comment by 1kidvidiot** [comment]
Just to expand on this, I manually changed the URL to the FQDN and it still works - it seems like clicking on the Check List links just spawn the native internal domain (ucs...) but it still runs fins if you manually change it to the domain name that works with the SSL certificate ... thanks for looking at it!

![Wekan 3](https://user-images.githubusercontent.com/18040392/62389889-d4c2fd00-b515-11e9-9d04-8c79b7e016ba.JPG)

**Comment by Seebahn** [comment]
Hi to all. Unfortunately, I ran into the same issues. I am using the wekan app on an UCS@School server and have set the outer FQDN properly. Up to the point of clicking on existing lists everything works like a charm. From there onwards, wekan spawns the internal URL (without SSL) and produces a blank screen. Quite a pity. Are there any known solutions to that?
Cheers, Axel from Northern Germany

P.S.: UCS@School as well as wekan itself are up to date.

**Comment by smidt** [comment]
There's a second issue here: #2

**Comment by Seebahn** [comment]
Cheers, mate.

 

Mit freundlichen Grüßen


Axel Seebahn



 

Institut für Qualitätsentwicklung an Schulen

Schleswig-Holstein (IQSH)

des Ministeriums für Bildung, Wissenschaft und Kultur
des Landes Schleswig-Holstein

 

IT-Beratung und Schulung / IQSH 433

Schreberweg 5

24119 Kronshagen

 

0431 5403-183

 <mailto:axel.seebahn@iqsh.de> axel.seebahn@iqsh.de

http://iqsh.schleswig-holstein.de <http://iqsh.schleswig-holstein.de/> 

https://twitter.com/_IQSH 

 

Von: Michel Smidt [mailto:notifications@github.com] 
Gesendet: Donnerstag, 29. August 2019 12:14
An: wekan/univention <univention@noreply.github.com>
Cc: Seebahn <axel.seebahn@iqsh.de>; Comment <comment@noreply.github.com>
Betreff: Re: [wekan/univention] Feature Request: Set Wekan ROOT_URL to FQDN on Univention. Not internal IP address. (#1)

 

There's a second issue here: #2 <https://github.com/wekan/univention/issues/2>

**Comment by xet7** [comment]
There will be more configuration options in next Wekan release for Univention. When it has been released, I will close this issue.

**Comment by xet7** [comment]
This same issue is also discussed here:
https://help.univention.com/t/wekan-wrong-card-adress/12787/6

And accounts lockout setting discussed here, that also needs to be added to web UI:
https://help.univention.com/t/wekan-nach-reboot-kein-login-mehr-moglich/12850/4

**Comment by 1kidvidiot** [comment]
Updated Wekan today and it works great! SSL intact and correct FQDN used! Thank you so much!

**Comment by xet7** [comment]
Hmm, maybe someone at Univention updated Wekan, because I did not do it yet. I'll try how it works on my Univention VM.

**Comment by xet7** [comment]
Well, it did say "update to v3.02" but in Wekan Admin Panel version is still v2.74. I think someone at Univention just did some update so settings so that FQDN does work. I will look how to upgrade to newer Wekan.

**Comment by xet7** [comment]
Anyway, FQDN works. I did setup Wekan v3.42 to run tests, if those are successfull then probably that Wekan version will be released sometime this or next week.

**Comment by bjo81** [comment]
So
```
ServerName wekan.foo.tld
ProxyPass / http://127.0.0.1:40002/wekan retry=0
ProxyPassReverse / http://127.0.0.1:40002/wekan
```

should work now with the corresponding ROOT_URL set? Here it produces still a white page.

**Comment by xet7** [comment]
@bjo81 

For ROOT_URL, click `APP SETTINGS`:

![uni1](https://user-images.githubusercontent.com/15545/65144949-173a8d80-da21-11e9-93d1-a0b91e074f36.png)

There change ROOT_URL:

![uni2](https://user-images.githubusercontent.com/15545/65144984-2ae5f400-da21-11e9-9d0d-c4775043e6b5.png)

Here is Apache settings:

https://github.com/wekan/wekan/wiki/Apache

**Comment by bjo81** [comment]
Thanks for the hint to the Apache config. The websockets part was missing, surprisingly the setup had 2 autogenerated configs for wekan, one in ucs-sites.conf.d with all 3 Proxy-related entries and one in 000-default where the websockets part was also missing.

**Comment by xet7** [comment]
@bjo81 

Apache config issue moved to #4

**Comment by lwillek** [comment]
> @bjo81
> 
> For ROOT_URL, click `APP SETTINGS`:

Just as a small reference: In addition to configuration via web console, these settings can be adapted via cli too.
The program used by Univention is named `univention-app`. Execute this program as user `root`.
See `univention-app configure --help` for all configuration options.

Some examples:
#### list current settings:
```
root@ucstest17:~# univention-app configure --list wekan
wekan/ROOT_URL: 'https://example.org/wekan' (ROOT_URL for Wekan URL)
wekan/ACCOUNTS_LOCKOUT_KNOWN_USERS_FAILURES_BEFORE: '5' (ROOT_URL for Wekan URL)
```
#### reconfigure `ROOT_URL` 
```
root@ucstest17:~# univention-app configure --set wekan/ROOT_URL='https://example.net/wekan' --autostart yes wekan
...
... [ plenty of output has been removed here ]
... [ the adjusted settings are applied and the container will be restarted ]
...
Setting overview variables
Reloading apache2 configuration (via systemctl): apache2.service.
````
