### ISSUE TITLE
Wekan docker-compose.yml changes are not recognized

### ISSUE THREAD

**Issue by thomasfrenkler** [wekan/univention#11]
Dear Wekan Friends,

we use Univention 4.4-4 and Wekan.
Actually my base problem is, that the E-Mail address from our LDAP(received froma MS-AD) User not the right one in wekan. (The other issue allready in discussion).
But during my test i have recognized that my smtp settings not working properly. (i will write another issue for that)
Now if i change some settings inside the Wekan docker-compose.yml and restart wekan, the setup for wekan will not adapt the changes. Only the "univention-app configure --set ..... option works fine but with this i am not able to set other options than the four implemented in the univention-app configure.  

Any ideas why changing the options in the docker-compose.yml not work.

Thanks
Thomas

**Comment by xet7** [comment]
See https://github.com/wekan/univention/issues/1#issuecomment-532644339
