### ISSUE TITLE
Can't access one board anymore

### ISSUE THREAD

**Issue by boospy** [wekan/univention#13]
Hello All, 

using here Wekan 4.01.0 on UCS 4.4.x. One board that is an Overview of some other board cards, so they are linked with. So for about 2 weeks, i can't load the board anymore. I can see the board, an i can click the board, but it is loading for ever. A reboot did not help. 

So what you need that you can help me to give me access again to this one board?

Very thanks :) :)

**Comment by xet7** [comment]
https://github.com/wekan/wekan/issues/1885

```
sudo su
docker exec -it wekan-db bash
mongo
use wekan
show collections
db.cards.find()
```
Etc.

And look at MongoDB 3.2.x docs, for mongo cli commands.

https://github.com/wekan/wekan/wiki/Backup

These are some tips, that I had a little time to write now.

**Comment by edgarvenom** [comment]
i don't use docker, i install  white snap

**Comment by xet7** [comment]
@edgarvenom 

Then you can use nosqlbooster GUI to connect through SSH to server localhost port 27019 and edit

**Comment by boospy** [comment]
This is exactly this Bug: https://gitmemory.com/issue/wekan/wekan/2492/504653688 but what can i do? Some lists are not accessable anymore. Not even in the mobile interface. We started also to repair the database. But it seems everything ok.

**Comment by xet7** [comment]
@boospy 

Why do you link to gitmemory and not to actual issue?

**Comment by boospy** [comment]
> @boospy
> 
> Why do you link to gitmemory and not to actual issue?

This is that what we find. And it look likes the same on this board we have. If you find out the same bug report here. It would be nice. 

Very Thanks.
