### ISSUE TITLE
BUG: possibly missing garbage collection? serverload is raising over time until restart server/wekan

### ISSUE THREAD

**Issue by chrisi51** [wekan/univention#16]
Hey @xet7, we noticed some special behavier in our server monitoring. 

We are using Univention UCS and have one wekan instance installed. We can watch the serverload raising over time, when we dont reboot the ucs instance or update the wekan app for a while so that it is just running without interruption.

The installed version at the moment is 4.95 - we gonna update as soon, 5.04/5.05 is available on ucs.

Im not sure if this is really related to UCS.

![image](https://user-images.githubusercontent.com/2156760/110699785-85fc3f80-81ef-11eb-8523-edb2e2ff240d.png)
after restarting the wekan app at 21:50:
![image](https://user-images.githubusercontent.com/2156760/110699935-ab894900-81ef-11eb-8b25-991138dd0209.png)
the main process which is raising is `node`

We are also running rocketchat on this server but if i turn off rocketchat it does not change the load so im pretty sure that wekan is the problem in that case. After restarting wekan, load is down to < 10%. 

If you need any further information, just ask for and i try to provide them. 

On another host, where wekan is running on native docker, i dont see this problem but this wekan instance is not used very much and also only by one user (me).

**Comment by xet7** [comment]
@chrisi51

[Wekan v5.04 has speed improvement](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v504-2021-03-07-wekan-release), it could be I have not yet released it for Univention yet. I think I'll make new release v5.05 and also send it to Univention, so they will test and release it in near future.

I would think on other host running on native docker, it could be maybe be running newest Wekan that already has speedup?

**Comment by xet7** [comment]
@chrisi51 

I did ask feedback about that speed improvement here https://github.com/wekan/wekan/issues/3345#issuecomment-792310430 but nobody has responded yet. Anyway, at my own server it had very noticeable speedup and lowering of CPU usage.

**Comment by chrisi51** [comment]
> I would think on other host running on native docker, it could be maybe be running newest Wekan that already has speedup?

@xet7 nope, on my local docker installation i even run 4.93 =)
i just also saw the newest update where u made some improvements.

But could be interesting, to try this update on the univention machine. And btw. it will take some days or even weeks to see the load raising so it may take a while to know more about that update. If it helps or not.

**Comment by xet7** [comment]
@chrisi51 

Wekan v5.05 has been released, please test does it help, or does load still raise.

Moved to https://github.com/wekan/wekan/issues/3345#issuecomment-792310430 , please add details there when you have them.

**Comment by chrisi51** [comment]
ok, i will install 5.05 and keep u updated in https://github.com/wekan/wekan/issues/3345#issuecomment-792310430

**Comment by xet7** [comment]
I mean, Wekan v5.05 is now also released for Univention.

**Comment by chrisi51** [comment]
yep i understood ... its already installed now and we keep u up-to-date if the load is still raising ... i guess we should monitor it for a week now
