### ISSUE TITLE
Installation of wekan.schema fails

### ISSUE THREAD

**Issue by werdck** [wekan/univention#17]
I don't get much more info from the logs.
Full log here: https://pastebin.com/fLrshrKE

**Comment by xet7** [comment]
@werdck 

That pastebin does not exist anymore. Please attach it in .zip file to comment of this issue instead.

**Comment by werdck** [comment]
[appcenter.log.zip](https://github.com/wekan/univention/files/6799371/appcenter.log.zip)
Here's an updated log from just now

**Comment by werdck** [comment]
[appcenter.log.zip](https://github.com/wekan/univention/files/6799477/appcenter.log.zip)

Here's an updated log from just now, showing the same error.
I of cause redacted all the DN and other sensitive data. If you need those, just ask and I'll dm you the full log @xet7

**Comment by werdck** [comment]
Is there anything new on this issue?
We need wekan quite desperately, is there a way to shift the data from our old univention-wekan install to a fresh wekan detatched from univention?

**Comment by xet7** [comment]
@werdck 

You can:
1. SSH to your Univention appliance, like: `ssh Administrator@ip-address`
2. Backup your wekan-db docker container to dump directory https://github.com/wekan/wekan/wiki/Backup
3. scp that dump directory to elsewhere
4. Setup new Wekan with docker-compose.yml from https://github.com/wekan/wekan
5. Restore dump like mentioned at https://github.com/wekan/wekan/wiki/Backup

**Comment by werdck** [comment]
@xet7 

Thank you for the quick answer and solution.
Seems like univention deleted the container data during my tries to upgrade though, so there is nothing left to restore.
My fault.

Great example of why one should always have backups!
