### ISSUE TITLE
Description save button not working

### ISSUE THREAD

**Issue by cmalderez** [wekan/univention#18]
Hello

I'v juste updated wekan to v5.78.0 in my univention instance
I've noticed that when creating or editing a cart, the description save button is not working
No way to save the description text

any idea ?

**Comment by xet7** [comment]
@cmalderez 

Hmm? I will test does that happen.

**Comment by cmalderez** [comment]
Other fields are working (title, checklists, subtasks, activities) ...
I'm running univention v4.4, cannot upgrade to v5 because I'm using OpenProject and log file says "because the following Apps are not available for UCS 5.0: * OpenProject", but i don't think it's linked

**Comment by xet7** [comment]
@cmalderez 

When I tried WeKan v5.78 at UCS 5.0, saving description does work. It's same WeKan for UCS4.4 and newer. Please check Admin Panel / Version about what WeKan version you are running.

**Comment by xet7** [comment]
I don't see OpenProject at UCS 5.0 App Center.

**Comment by xet7** [comment]
Also please check have you installed all WeKan updates.

**Comment by cmalderez** [comment]
true, that's why I can't upgrade to UCS v5.0 ... 
Anyway, I've updated Wekan to v5.78

Here is the version dump from admin panel : 

![image](https://user-images.githubusercontent.com/6955611/143284218-0a1724cb-ee77-4fc2-bad8-322484d62a1f.png)

**Comment by xet7** [comment]
@cmalderez 

Please clear all browser cache, close browser, open browser, and login to WeKan again. Then try does saving description of card work.

**Comment by cmalderez** [comment]
Done, same issue

I'm using Chrome 83.0.4103.116 ... could it be this ?

**Comment by xet7** [comment]
@cmalderez 

Try Firefox.

**Comment by cmalderez** [comment]
I've tested with chrome 94, it works .. :/
Cannot test firefox, I'm at work and no way to install apps and update chrome :/

Thanks for your help anyway :)

**Comment by xet7** [comment]
Thanks! Nice that it works with Chrome 94 !
