### ISSUE TITLE
Feature request: configure ROOT_URL

### ISSUE THREAD

**Issue by mbunkus** [wekan/univention#2]
One of our customers using the UCS Wekan app wants to have it accessible from the internet. We have a reverse proxy that proxies Wekan just fine. However, Wekan often redirects to the URL given with the Docker container's `ROOT_URL` environment variable, which is the server's FQDN — which is obviously not reachable from the internet.

I'm aware that the app's page in the app center states that the `ROOT_URL` must/can be configured, but it gives no indication how that can actually be done. The app's configuration page doesn't offer such a setting, and meddling with the Docker composer file template seems brittle.

**Comment by smidt** [comment]
Same issue here

**Comment by xet7** [comment]
There will be more configuration options in next Wekan release for Univention. When it has been released, I will close this issue.

**Comment by xet7** [comment]
Moved to #1
