### ISSUE TITLE
Cannot join domain, cannot use cli install

### ISSUE THREAD

**Issue by bolduant** [wekan/univention#3]
Hello,
Using univention wekan appliance install wizards end up in error message "No domain controller was found at the address of the name server". All needed SRV records are installed. Unfornutaley there is no cli i can use or text based installer. 
The wekan appliance is not troublehootable. 

Can anyone help me?

**Comment by xet7** [comment]
Have you upgraded to Wekan v3.02 ? Is this related to FQDN at #1 ?

Here is video how Wekan appliance is installed:
https://wekan.github.io/UCS-4.4-with-wekan-10.200.2.25.webm

Unfortunately I don't have domain controller where I could test it.
