### ISSUE TITLE
Wekan SMTP settings on Univention?

### ISSUE THREAD

**Issue by xet7** [wekan/univention#6]
Moved to here from [Wekan community](https://community.vanila.io/?t=a3733bc3-df34-493d-a160-e526f3c18b9d)

From Adri:

Hello to everyone,

I'm Adri and I'm the IT man at a 25 employee business.

I've installed Wekan with Univention platform and now I'm doing some testing. I want to implement this system for my users.

I've configured the SMTP connection but just isn't working. I've tested the SMTP credentials and server and all is working fine, but not with Wekan.

How can I fix this?

![Wekan_SMTP_on_Univention](https://user-images.githubusercontent.com/15545/65374186-a77e0a00-dc8f-11e9-9f0e-fbba2ffcd488.png)

Thanks and greetings!

Adri

**Comment by xet7** [comment]
Yes there are these settings at Admin Panel, but there is also same settings elsewhere that I should add to Wekan app config options. Those other settings need to be set too, for SMTP to work.

New settings will be available later in new Wekan version for Univention. In Univention updates you will see when there is new update for Wekan.

**Comment by poroj** [comment]
@xet7 "es gibt auch dieselben Einstellungen an anderer Stelle, die ich zu den Wekan-App-Konfigurationsoptionen hinzufügen sollte. "
wo befindet sich diese Stelle ??

Danke!

**Comment by xet7** [comment]
@poroj

## 1) Wekan product page, scroll down

![ucs-mail-1](https://user-images.githubusercontent.com/15545/78279227-e682f700-751f-11ea-83fc-d22bc71b77fb.png)

## 2) Click APP SETTINGS

![ucs-mail-2](https://user-images.githubusercontent.com/15545/78279301-fdc1e480-751f-11ea-9d7b-1632c71cd79a.png)

## 3) Mail Settings

https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

![ucs-mail-3](https://user-images.githubusercontent.com/15545/78279359-129e7800-7520-11ea-9e22-a911826285ba.png)

## 4) This below is usually not required

( Login to Wekan as admin LDAP group user. Click right top your Username / Admin Panel / Settings / Email ).
