### ISSUE TITLE
Root Url 

### ISSUE THREAD

**Issue by hkocaoglu** [wekan/univention#7]
Hi All, 

@hkocaoglu

Univention has Docker version of Wekan, and these web-based ROOT_URL settings:
wekan/univention#1 (comment)

You should not install Snap, when using Univention Wekan. Univention Wekan is integrated directly to Univention user management of normal and admin users, as is mentioned at:
https://github.com/wekan/wekan/wiki/Platforms and https://github.com/wekan/univention

For other Univention Wekan related questions, please add to https://github.com/wekan/univention/issues . Thanks!

I made the settings for ROOT_URL as described above and cliked apply settings buttton on the Univention Web interface and it worked properly.

I am using Wekan at my local network , so ROOT_URL was 192.168.1.42 at the beginning and i mada changes on web interface  then ROO_URL became 192.168.43.12.  

But then i wanted to switch back original settings (to 192.168.1.42), but it is not working anymore. ROOT_URL is still 192.168.43.12. 

If it is possible to change ROOT_URL manually inside server , it will be better solution for me . 

Thanks.

UCR Version : 4.4.1
Wekan Version : 3.42

**Comment by xet7** [comment]
See https://github.com/wekan/univention/issues/1#issuecomment-532644339
